// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOT260enO-7EpZZdX_QuU_JpF4q_lQKTw',
    appId: '1:1043979341460:web:3583220aa6e875eb50ee81',
    messagingSenderId: '1043979341460',
    projectId: 'flutter-test-73f23',
    authDomain: 'flutter-test-73f23.firebaseapp.com',
    storageBucket: 'flutter-test-73f23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0SJmcp0EzrN-TmLIVDPoGety-61GV9kQ',
    appId: '1:1043979341460:android:a9cf33b3b7b796a350ee81',
    messagingSenderId: '1043979341460',
    projectId: 'flutter-test-73f23',
    storageBucket: 'flutter-test-73f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAfycAXDCRtzNfM-sSNCwKLWglgq_WY8',
    appId: '1:1043979341460:ios:d34df4863134a14f50ee81',
    messagingSenderId: '1043979341460',
    projectId: 'flutter-test-73f23',
    storageBucket: 'flutter-test-73f23.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUAfycAXDCRtzNfM-sSNCwKLWglgq_WY8',
    appId: '1:1043979341460:ios:d34df4863134a14f50ee81',
    messagingSenderId: '1043979341460',
    projectId: 'flutter-test-73f23',
    storageBucket: 'flutter-test-73f23.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
